postgresql:
  service:
    type: NodePort
redis:
  master:
    service:
      type: NodePort
  slave:
    service:
      type: NodePort

orderservice:
  image:  amiedeep/orderservice
  tag: 1.0.0
  pullPolicy: IfNotPresent