version: "3.3"
services:
  orderservice:
    build:
      context: ./orderservice
    ports: 
      - 8081:8081
  redis:
    image: redis
    ports:
      - 6379:6379
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831
      - 16686:16686

