postgresql:
  postgresqlUsername: postgres
  postgresqlPassword: admin
  service:
    type: NodePort
redis:
  usePassword: false
  master:
    service:
      type: NodePort
      # nodePort: 30001
  slave:
    service:
      type: NodePort
orderservice:
  service:
    type: NodePort
    nodePort: 30003
  image:
    repository: amiedeep/orderservice
    tag: 1.2.1
    pullPolicy: IfNotPresent
  redis:
    host: demo-app-redis-master 

customerservice:
  service:
    type: NodePort
    nodePort: 30004
  image:
    repository: amiedeep/customerservice
    tag: 1.0.0
    pullPolicy: IfNotPresent
  postgres:
    host: demo-app-postgresql
jaegeragent:
  host: jaeger-agent
  port: 6831