apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "helm-chart.orderservice.fullname" . }}
  labels:
    app: {{ template "helm-chart.orderservice.name" . }}
    chart: {{ template "helm-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "helm-chart.orderservice.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "helm-chart.orderservice.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "helm-chart.orderservice.name" . }}
        image: "{{ .Values.orderservice.image.repository }}:{{ .Values.orderservice.image.tag }}"
        imagePullPolicy: {{ .Values.orderservice.image.pullPolicy }}
        env:
          - name: REDIS_URL
            value: {{ .Values.orderservice.redis.host | quote }}
          - name: JAEGER_AGENT_HOST
            value: {{ .Values.jaegeragent.host | quote }} 
          - name: JAEGER_AGENT_PORT
            value: {{ .Values.jaegeragent.port | quote }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP